### ISSUE TITLE
Build Failure: Failed to minify the code

### ISSUE THREAD

**Issue by Joldnine** [bendrucker/snakecase-keys#8]
```
> react-scripts build

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/snakecase-keys/node_modules/map-obj/index.js:4

Read more here: http://bit.ly/2tRViJ9

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! proj@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the proj@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/10.7.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.2.0
3 info using node@v10.7.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle proj@0.1.0~prebuild: proj@0.1.0
6 info lifecycle proj@0.1.0~build: proj@0.1.0
7 verbose lifecycle proj@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle proj@0.1.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/mac/Develop/workspace/proj/proj/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Python.framework/Versions/3.7/bin
9 verbose lifecycle proj@0.1.0~build: CWD: /Users/mac/Develop/workspace/proj/proj
10 silly lifecycle proj@0.1.0~build: Args: [ '-c', 'react-scripts build' ]
11 silly lifecycle proj@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle proj@0.1.0~build: Failed to exec build script
13 verbose stack Error: proj@0.1.0 build: `react-scripts build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
14 verbose pkgid proj@0.1.0
15 verbose cwd /Users/mac/Develop/workspace/proj/build
16 verbose Darwin 17.7.0
17 verbose argv "/usr/local/Cellar/node/10.7.0/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v10.7.0
19 verbose npm  v6.2.0
20 error code ELIFECYCLE
21 error errno 1
22 error proj@0.1.0 build: `react-scripts build`
22 error Exit status 1
23 error Failed at the proj@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

With a create-react-app project, it works well in dev mode, but it fails to build.

**Comment by bendrucker** [comment]
The code here is totally valid, I can't comment on your build setup and how to fix it. If you read the error more carefully you'll see it's `map-obj` which is a dependency of this module. I'd discourage you from filing another issue there—minification errors are up to the builder, not module authors. If it's valid JS it's the minifier's job to work with it.
